coverage:
  precision: 2
  round: up
  range: "0...100"
  status:
    project:
      default:
        target: 0
        threshold: 100%
        paths:
          - "src"
    patch:
      default:
        target: 0
        threshold: 100%
        paths:
          - "src"
