name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Package
        run: make dist

      - name: Upload package
        uses: actions/upload-artifact@master
        with:
          name: git-draft.zip
          path: ${{ github.workspace }}/dist/git-draft.zip
