name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Process test reports
        run: make process-reports

      - name: Package
        run: make dist VERSION="$GITHUB_SHA"

      - name: Upload package
        uses: actions/upload-artifact@master
        with:
          name: git-draft.zip
          path: ${{ github.workspace }}/dist/git-draft.zip

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/cobertura.xml
          flags: unittests
