name: Release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Changelog
        id: changelog
        run: |
          contents="$(sed -e '1,/##/d' -e '/##/,$d' CHANGELOG.md)"
          contents="${contents//'%'/'%25'}"
          contents="${contents//$'\n'/'%0A'}"
          contents="${contents//$'\r'/'%0D'}"
          echo "::set-output name=contents::$contents"

      - name: Create release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.contents }}
          draft: false
          prerelease: false

      - name: Upload build
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build/git-draft
          asset_name: git-draft.sh
          asset_content_type: text/plain
